[MI-1999] Add readme/docs
Brightscout/mattermost-plugin-azure-devops pull request #15
Opened 2022-07-29 09:07 UTC by ayusht2810

2022-08-10 06:32 UTC, raghavaggarwal2308 requested changes

2022-08-10 06:32 UTC, raghavaggarwal2308 commented on README.md
> +This plugin integrates the services of Azure DevOps in Mattermost. For a stable production release, please download the latest version from the [Github Release](https://github.com/Brightscout/matterm
```suggestion
This plugin integrates the services of Azure DevOps in Mattermost. For a stable production release, please download the latest version from the [Github Release](https://github.com/Brightscout/mattermost-plugin-azure-devops/releases) and follow the instructions to [install](#installation) and [configure](#setup) the plugin.
```

2022-08-10 06:32 UTC, raghavaggarwal2308 commented on README.md
> +- Link a project: You can link a project existing on Azure DevOps using the slash command below.
```suggestion
- Link a project: You can link an existing Azure DevOps project using the slash command below.
```

2022-08-10 06:32 UTC, raghavaggarwal2308 commented on README.md
> +- Unink a project: You can unlink a project appearing in the RHS under "Linked Projects".
```suggestion
- Unlink a project: You can unlink a project appearing in the RHS under "Linked Projects".
```

2022-08-10 06:32 UTC, raghavaggarwal2308 commented on README.md
> +## Connecting to Azure Devops
```suggestion
## Connecting to Azure Devops

```

2022-08-10 06:32 UTC, raghavaggarwal2308 commented on docs/oauth_setup.md
> +  - For the "Application website" put the link of your Mattermost server, for example: If the Mattermost server is running on `http://mymmserver.com` then the value would be `http://mymmserver.com` a
```suggestion
  - For the "Application website" put the URL of your Mattermost server, for example: If the Mattermost server is running on `http://mymmserver.com` then the value would be `http://mymmserver.com` and "Authorization callback URL" will be `http://mymmserver.com/plugins/mattermost-plugin-azure-devops/api/v1/oauth/complete`
```

2022-08-10 06:32 UTC, raghavaggarwal2308 commented on docs/oauth_setup.md
> +  - Fill in details like Company name, Application name.
```suggestion
  - Fill in details like Company name and Application name.
```

2022-08-10 06:32 UTC, raghavaggarwal2308 commented on docs/oauth_setup.md
> +  - Under "Authorized scopes" check "Work items(full)" and "Code(read)".
```suggestion

  - Under "Authorized scopes" check "Work items(full)" and "Code(read)".
```

2022-08-10 06:32 UTC, raghavaggarwal2308 commented on docs/oauth_setup.md
> +  - Click on "Create application".
```suggestion

  - Click on "Create application".
```

2022-08-10 06:32 UTC, raghavaggarwal2308 commented on docs/plugin_setup.md
> +    - **Encryption Secret**: Regenerate a new encryption secret.
Also mention what is this `Encryption Secret` used for

2022-08-10 06:32 UTC, raghavaggarwal2308 commented on docs/oauth_setup.md
> +  - On successful creation, you will be navigated to a page having App ID, App Secret, and Client Secret
Add a note that you will need these value later while configuring the plugin

2022-08-10 06:32 UTC, raghavaggarwal2308 commented on README.md
> +  - [oAuth app registration for Azure DevOps](./docs/oauth_setup.md)
```suggestion
  - [OAuth app registration for Azure DevOps](./docs/oauth_setup.md)
```

2022-08-10 06:32 UTC, raghavaggarwal2308 commented on README.md
> +  - You will get a response with a link to connect your Azure DevOps account.
```suggestion
  - You will get a response with a link to connect your Azure DevOps account.
  
```

2022-08-10 06:32 UTC, raghavaggarwal2308 commented on docs/oauth_setup.md
> +    ![Screenshot from 2022-07-29 13-24-47](https://user-images.githubusercontent.com/100013900/181712515-89efdb18-0f51-4194-b954-c0edb4188423.png)
```suggestion

    ![Screenshot from 2022-07-29 13-24-47](https://user-images.githubusercontent.com/100013900/181712515-89efdb18-0f51-4194-b954-c0edb4188423.png)
```

2022-09-05 11:59 UTC, avas27JTG commented
chnages of this PR is no longer updated closing this as doc. have been created separately

2022-09-05 11:59 UTC, closed without merging