[MI-2057] Integrate subscription list page
Brightscout/mattermost-plugin-azure-devops pull request #41
Opened 2022-08-17 07:05 UTC by ayusht2810

2022-08-17 10:00 UTC, raghavaggarwal2308 requested changes

2022-08-17 10:00 UTC, raghavaggarwal2308 commented on webapp/src/containers/Rhs/index.tsx
> +                        <ProjectDetails {...getProjectDetailsState(usePlugin.state)}/> :
Create a variable for `getProjectDetailsState(usePlugin.state)`

2022-08-17 10:42 UTC, raghavaggarwal2308 approved these changes

2022-08-17 16:07 UTC, muazzamqazi commented on webapp/src/containers/Rhs/projectDetails/index.tsx
> +        };
```suggestion
        return handleResetProjectDetails;
```

2022-08-17 16:09 UTC, muazzamqazi commented on webapp/src/containers/Rhs/projectDetails/index.tsx
> +                    onClick={() => handleUnlinkProject()}
```suggestion
                    onClick={handleUnlinkProject}
```

2022-08-17 16:11 UTC, muazzamqazi approved these changes

2022-09-05 08:04 UTC, avas27JTG approved these changes

2022-09-05 08:04 UTC, avas27JTG commented on server/plugin/api.go
> +		p.API.LogError("Error in getting channels for team and user", "Error", channelErr.Error())
create constant for msgs

2022-09-05 08:04 UTC, avas27JTG commented on webapp/src/containers/Rhs/projectDetails/index.tsx
> +
most of the content of this has been refactored so, leaving those

2022-09-06 08:03 UTC, avas27JTG commented
Changes picked here https://github.com/Brightscout/mattermost-plugin-azure-devops/pull/69

2022-09-06 08:03 UTC, closed without merging