[MI-2073] Add test cases for API
Brightscout/mattermost-plugin-azure-devops pull request #48
Opened 2022-08-23 12:26 UTC by ayusht2810

2022-08-23 17:56 UTC, raghavaggarwal2308 requested changes

2022-08-23 17:56 UTC, raghavaggarwal2308 commented on server/plugin/api_test.go
> +			p.handleAuthRequired(timerHandler)
check something here

2022-08-24 07:24 UTC, raghavaggarwal2308 approved these changes

2022-09-05 08:15 UTC, avas27JTG commented on server/plugin/api_test.go
> +			description: "test CreateTask",
```suggestion
			description: "CreateTask: valid fields",
```
same as previous PR comment
https://github.com/Brightscout/mattermost-plugin-azure-devops/pull/47#pullrequestreview-1096035931

2022-09-05 12:32 UTC, avas27JTG approved these changes

2022-09-06 09:29 UTC, merged