[MI-2199]: Made changes on server to add constraints on project/channel visibility on subscription cards.
Brightscout/mattermost-plugin-azure-devops pull request #83
Opened 2022-10-04 09:39 UTC by avas27JTG

Made changes on server to add constraints on project/channel visibility on subscription cards.

2022-10-05 08:04 UTC, Kshitij-Katiyar commented on server/plugin/utils.go
> +func (p *Plugin) GetSubscriptionsForOnlyAccessibleChannelsOrProjects(subscriptionList []*serializers.SubscriptionDetails, teamID, mattermostUserID string) ([]*serializers.SubscriptionDetails, error)
```suggestion
func (p *Plugin) GetSubscriptionsForAccessibleChannelsOrProjects(subscriptionList []*serializers.SubscriptionDetails, teamID, mattermostUserID string) ([]*serializers.SubscriptionDetails, error) {
```

2022-10-05 08:04 UTC, Kshitij-Katiyar commented on server/plugin/utils.go
> +		// For each subscripton on a project check if a user is an admin or member of the MM channel to return subscriptions
```suggestion
		// For each subscription on a project check if a user is an admin or member of the MM channel to return subscriptions
```

2022-10-05 08:04 UTC, Kshitij-Katiyar commented on webapp/src/services/index.ts
> +                url: `${Constants.pluginApiServiceConfigs.getSubscriptionList.path}/${params.team_id}`,
here we are sending the team id in path param as well as in body do we need to send this twice

2022-10-05 18:21 UTC, raghavaggarwal2308 requested changes

2022-10-05 18:21 UTC, raghavaggarwal2308 commented on server/constants/messages.go
> +	GetSubscriptionListError           = "Error getting Subscription List"
```suggestion
	GetSubscriptionListError           = "Error getting subscription list"
```

2022-10-05 18:21 UTC, raghavaggarwal2308 commented on server/plugin/api.go
> +			p.handleError(w, r, &serializers.Error{Code: statusCode, Message: constants.ErrorLinkProject})
```suggestion
			p.handleError(w, r, &serializers.Error{Code: subscriptionStatusCode, Message: constants.ErrorLinkProject})
```

2022-10-05 18:21 UTC, raghavaggarwal2308 commented on server/plugin/api_test.go
> +			description: "HandleGetSubscriptions: GetSubscriptionsForOnlyAccessibleChannelsOrProjects gives error",
```suggestion
			description: "HandleGetSubscriptions: GetSubscriptionsForAccessibleChannelsOrProjects gives error",
```

2022-10-06 10:12 UTC, Kshitij-Katiyar approved these changes

2022-10-06 15:03 UTC, manojmalik20 approved these changes

2022-10-06 15:03 UTC, manojmalik20 commented on server/plugin/utils.go
> +						filteredSubscriptionList = append(filteredSubscriptionList, subscription)
```suggestion
						filteredSubscriptionList = append(filteredSubscriptionList, subscription)
						break
```

2022-10-06 17:45 UTC, raghavaggarwal2308 approved these changes

2022-10-07 06:43 UTC, merged